name: taramail
include:
  - path: ./taracert/compose.dev.yml
services:
  api:
    volumes:
      - ./backend/taramail:/app/taramail
      - ./backend/alembic:/app/alembic
    command: >
      sh -c "alembic upgrade head && uvicorn --host=0.0.0.0 --port=80 taramail.api:app --log-config=/app/log-config.dev.yaml --reload"

  custom-exporter:
    volumes:
      - ./backend/taramail:/app/taramail
    environment:
      - LOG_LEVEL=DEBUG
    command: uvicorn --host=0.0.0.0 --port=80 taramail.exporter:app --reload

  dockerapi:
    volumes:
      - ./backend/taramail:/app/taramail
    environment:
      - LOG_LEVEL=DEBUG
    command: uvicorn --host=0.0.0.0 --port=80 taramail.dockerapi:app --reload

  memcached:
    command: memcached -vv

  socketmap:
    volumes:
      - ./backend/taramail:/app/taramail
    command: socketmap --log-level debug

  unbound:
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      start_period: 0s
      interval: 1s
      timeout: 1s
      retries: 1
